### ISSUE TITLE
skydip from SDTinspect

### ISSUE THREAD

**Issue by maupilia** [matteobachetti/srt-single-dish-tools#70]
Whenever I use SDTinspect on one directory where a skydip is present, the skydip is correctly classified, but SDTimage fails with a 
KeyError: "Extension 'DATA TABLE' not found."
(detail below).
The problem does not appear when I comment the skydip directory in my .ini file
-----
Traceback (most recent call last):
  File "/home/mpilia/anaconda/envs/py35/bin/SDTimage", line 11, in <module>
    load_entry_point('srttools==0.5.dev1015', 'console_scripts', 'SDTimage')()
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/srttools-0.5.dev1015-py3.5.egg/srttools/imager.py", line 1193, in main_imager
    avoid_regions=excluded_radec)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/srttools-0.5.dev1015-py3.5.egg/srttools/imager.py", line 172, in __init__
    self.get_opacity()
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/srttools-0.5.dev1015-py3.5.egg/srttools/imager.py", line 226, in get_opacity
    results = calculate_opacity(s)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/srttools-0.5.dev1015-py3.5.egg/srttools/opacity.py", line 47, in calculate_opacity
    data = hdulist['DATA TABLE'].data
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 313, in __getitem__
    self._positive_index_of(key))
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 709, in _positive_index_of
    index = self.index_of(key)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 690, in index_of
    raise KeyError('Extension {!r} not found.'.format(key))
KeyError: "Extension 'DATA TABLE' not found."

**Comment by matteobachetti** [comment]
@maupilia what command are you using exactly? Also, can you send me the fits file? Is it a standard fitszilla file? Does it _have_ a DATA TABLE?

**Comment by maupilia** [comment]
the problem is the summary.fits file in the skydip directory
