### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous

### ISSUE THREAD

**Issue by maupilia** [matteobachetti/srt-single-dish-tools#72]
Sometimes when I select a pixel with key "a", then, after I close the windows with the subscans, I receive the error message reported below and the window relative to the map gets automatically closed. 

-----------------------------------------

Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/tkinter/__init__.py", line 1558, in __call__
    return self.func(*args)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 488, in key_press
    FigureCanvasBase.key_press_event(self, key, guiEvent=event)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 1861, in key_press_event
    self.callbacks.process(s, event)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/cbook.py", line 554, in process
    proxy(*args, **kwargs)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/cbook.py", line 416, in __call__
    return mtd(*args, **kwargs)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/srttools-0.5.dev1018-py3.5.egg/srttools/interactive_filter.py", line 497, in on_key
    self.fun(x, y, key)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/srttools-0.5.dev1018-py3.5.egg/srttools/imager.py", line 699, in rerun_scan_analysis
    self.reprocess_scans_through_pixel(x, y, test=test)
  File "/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/srttools-0.5.dev1018-py3.5.egg/srttools/imager.py", line 718, in reprocess_scans_through_pixel
    if info != empty:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by maupilia** [comment]
that error seems indeed to have disappeared. What was also probably causing it might still be there though.

I often saw it combined with this warning:

/home/mpilia/anaconda/envs/py35/lib/python3.5/site-packages/srttools-0.5.dev1036-py3.5.egg/srttools/imager.py:489: RuntimeWarning: invalid value encountered in sqrt
  img_sdev = np.sqrt(img_sdev)

Now, when this happens, the window is not automatically closed but, nonetheless, the flagging is not applied.
